### ISSUE TITLE
Fix bug when writing file

### ISSUE THREAD

**Issue by fhightower** [fhightower/biblioteca#10]
Getting this error when trying to write a file:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.9/site-packages/democritus_utility/utility.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/code/biblioteca/hub.py", line 69, in add
    _save_data(raw_data, enriched_data, meta_data, name)
  File "/code/biblioteca/hub.py", line 53, in _save_data
    file_write(os.path.join(BASE_PATH, f'{name}.raw'), raw_data)
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/files.py", line 61, in file_write
    result = _file_active_action(file_path, 'w', file_contents)
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/files.py", line 16, in _file_active_action
    length_of_content = _file_action(file_path, '{}+'.format(base_mode), 'write', file_contents)
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/files.py", line 34, in _file_action
    with atomic_write(file_path, mode=mode) as f:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/atomic_writes.py", line 28, in atomic_write
    with atomic_write_(fpath, writer_cls=AtomicWriterPerms, overwrite=overwrite, **cls_kwargs) as f:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/atomicwrites/__init__.py", line 166, in _open
    with get_fileobject(**self._open_kwargs) as f:
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/atomic_writes.py", line 13, in get_fileobject
    f = super().get_fileobject(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/atomicwrites/__init__.py", line 183, in get_fileobject
    descriptor, name = tempfile.mkstemp(suffix=suffix, prefix=prefix,
  File "/usr/local/lib/python3.9/tempfile.py", line 332, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/root/biblioteca/tmp3db3xy1f'
```

Here is a script to replicate this issue:

```python
from biblioteca import hub

l = ['http://recursivedrawing.com/']

for i in l:
    print(i)
    hub.add(i)
```

**Comment by fhightower** [comment]
The problem is that I am running this script in docker, so I need to update hub.py to write to the proper directory in the docker container and I need to update docker-compose.yml to mount the directory in which the user would like to store the files (I'm addressing this in #9).
