### ISSUE TITLE
Examine errors to identify root causes

### ISSUE THREAD

**Issue by fhightower** [fhightower/biblioteca#12]
I ran into some errors when trying to collect from various sites. I've logged these errors in a secret gist and will be addressing them soon.

**Comment by fhightower** [comment]
Getting this error when trying to save PDF content:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/democritus_utility/utility.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/code/biblioteca/hub.py", line 76, in add
    raw_data, enriched_data, meta_data = _get_data(url)
  File "/code/biblioteca/hub.py", line 36, in _get_data
    raw_data = get(new_data, process_response=True)
  File "/usr/local/lib/python3.9/site-packages/democritus_networking/networking.py", line 63, in get
    result = _process_response(
  File "/usr/local/lib/python3.9/site-packages/democritus_networking/networking.py", line 30, in _process_response
    return json_read(response.text)
  File "/usr/local/lib/python3.9/site-packages/democritus_json/json_data.py", line 22, in json_read
    if file_exists(json_string):
  File "/usr/local/lib/python3.9/site-packages/democritus_file_system/files.py", line 191, in file_exists
    return os.access(file_path, os.F_OK)
ValueError: embedded null byte
```
